export const iconData = [
  { name: "HTML", path: "html.svg", proficiency: 90 },
  { name: "CSS", path: "css.svg", proficiency: 80 },
  { name: "JavaScript", path: "javascript.svg", proficiency: 75 },
  { name: "ReactJs", path: "react.svg", proficiency: 85 },
  { name: "Git", path: "git.svg", proficiency: 70 },
  { name: "Tailwind", path: "tailwind.svg", proficiency: 75 },
  { name: "Redux", path: "redux.svg", proficiency: 75 },
  { name: "GitHub", path: "github3.svg", proficiency: 70 },
  { name: "VScode", path: "vscode.svg", proficiency: 85 },
  { name: "NextJs", path: "nextJs2.svg", proficiency: 50 },
  { name: "Python", path: "python.svg", proficiency: 70 },
  { name: "Redux Toolkit", path: "redux-toolkit.svg", proficiency: 70 },
  { name: "Postman", path: "postman.svg", proficiency: 60 },
  { name: "Vite", path: "vite.svg", proficiency: 80 },
  { name: "nodeJs", path: "nodejs.svg", proficiency: 50 },
];
